### ISSUE TITLE
What url do I put for swap

### ISSUE THREAD

**Issue by sajsanghvi** [johra/spotify-token-parse-tutorial#1]
Hey man. Super helpful tutorial. 

So i deployed the cloud code to /cloud/main.js via my terminal, but what exact URL do I put as my refresh and swap URLs in my iOS sdk..just a little confused here

 Thank you!

**Comment by hbun** [comment]
I'm wondering the same thing. Working in an iOS project, this is my first time dealing with a token swap, and any additional information would be wonderful!

**Comment by johra** [comment]
Sorry for the late reply. In parse you will get a location for your cloud code, so in iOS you put the following:
let kTokenSwapServiceURL = "http://YOURAPPNAME.parseapp.com/swap"
let kTokenRefreshServiceURL = "http://YOURAPPNAME.parseapp.com/refresh"
